language: c
dist: trusty
sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - netcdf-bin libnetcdf-dev openmpi-bin libopenmpi-dev gfortran

script:
  # build UMD-LETKF
  - make

  # TODO: add the testing scripts