language: c
dist: trusty
sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gfortran
    - openmpi-bin libopenmpi-dev
    - libblas-dev liblapack-dev
    - netcdf-bin libnetcdf-dev 


before_script:
  - cd test; ./getTestData.sh; cd ../


script:
  - mkdir build; cd build; FC=mpif90 cmake ../ -DLETKF_ENABLE_TESTS=ON -DCMAKE_BUILD_TYPE=Debug -DLETKF_ENABLE_CODECOVERAGE=ON -DLETKF_ENABLE_GRIB=OFF;
  - make
  - make test



after_success:
  bash <(curl -s https://codecov.io/bash)