language: c
dist: trusty
sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gfortran libopenmpi-dev libblas-dev liblapack-dev libnetcdf-dev netcdf-bin 

script:
  # build UMD-LETKF
  - FC=mpif90 make

  # TODO: add the testing scripts