language: c
dist: trusty
sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gfortran libopenmpi-dev libblas-dev liblapack-dev libnetcdf-dev netcdf-bin 

script:
  - mkdir build; cd build; FC=mpif90 cmake ../ -DCMAKE_BUILD_TYPE=Debug -DENABLE_CODECOVERAGE=ON; make
  - ctest

after_success:
  bash <(curl -s https://codecov.io/bash)